[package]
name = "flatzinc"
version = "0.1.0"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "A flatzinc parser"
readme = "README.md"
documentation = ""
repository = "https://github.com/sthiele/flat-parser"
publish = false
edition = "2018"

[dependencies]
nom = "5.1"